development: &base
  adapter: postgresql
  database: sembl_development
  encoding: unicode
  host: localhost
  password:

production:
  <<: *base

test:
  adapter: postgresql
  database: sembl_test
  encoding: unicode
  host: localhost
  password:
