development: &base
  adapter: postgresql
  database: sembl_development
  encoding: unicode
  port: <%= ENV["BOXEN_POSTGRESQL_PORT"] || 5432 %>
  host: localhost
  password:

production:
  <<: *base

test:
  adapter: postgresql
  database: sembl_test
  encoding: unicode
  port: <%= ENV["BOXEN_POSTGRESQL_PORT"] || 5432 %>
  host: localhost
  password:
